export const tours = [
  {
    id: 1,
    title: "Jos City Heritage Tour",
    description: "Explore the colonial history and vibrant culture of Jos city center",
    image: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=500&h=400&fit=crop",
    price: 25000,
    duration: "4 hours",
    difficulty: "Easy",
    category: "Cultural",
    rating: 4.8,
    reviews: 124,
  },
  {
    id: 2,
    title: "Plateau Food Adventure",
    description: "Taste authentic Plateau cuisine and visit local food markets",
    image: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=500&h=400&fit=crop",
    price: 22000,
    duration: "5 hours",
    difficulty: "Easy",
    category: "Culinary",
    rating: 4.9,
    reviews: 156,
  },
  {
    id: 3,
    title: "Assop Falls & Nature Trek",
    description: "Hike to stunning waterfalls and experience Plateau's natural beauty",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop",
    price: 18000,
    duration: "6 hours",
    difficulty: "Moderate",
    category: "Adventure",
    rating: 4.7,
    reviews: 98,
  },
  {
    id: 4,
    title: "Arts & Crafts Workshop",
    description: "Learn traditional crafts from local artisans in Jos",
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=500&h=400&fit=crop",
    price: 15000,
    duration: "3 hours",
    difficulty: "Easy",
    category: "Cultural",
    rating: 4.6,
    reviews: 67,
  },
  {
    id: 5,
    title: "Sunset Photography Safari",
    description: "Capture stunning sunsets and landscapes with local photography guide",
    image: "https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?w=500&h=400&fit=crop",
    price: 20000,
    duration: "4 hours",
    difficulty: "Easy",
    category: "Photography",
    rating: 4.8,
    reviews: 89,
  },
  {
    id: 6,
    title: "Local Market & Bargaining Masterclass",
    description: "Learn to navigate Nigerian markets and haggle like a local",
    image: "https://images.unsplash.com/photo-1515182629504-727d7753751f?w=500&h=400&fit=crop",
    price: 12000,
    duration: "3 hours",
    difficulty: "Easy",
    category: "Cultural",
    rating: 4.5,
    reviews: 42,
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Sarah Johnson",
    location: "London, UK",
    text: "Timothy made my trip to Jos unforgettable. His passion for the culture is infectious!",
    rating: 5,
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
  },
  {
    id: 2,
    name: "Chinedu Okafor",
    location: "Lagos, Nigeria",
    text: "Best food tour I've ever done. The authenticity and stories behind each dish were amazing.",
    rating: 5,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
  },
  {
    id: 3,
    name: "Emma Williams",
    location: "New York, USA",
    text: "The Assop Falls trek was breathtaking. A truly hidden gem in Nigeria.",
    rating: 5,
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
  },
];

export const podcastEpisodes = [
  {
    id: 1,
    title: "Starting Your Travel Business",
    description: "Timothy shares insights on launching a successful tourism venture",
    date: "2024-03-15",
    duration: "45 mins",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&h=300&fit=crop",
    audioUrl: "#",
  },
  {
    id: 2,
    title: "Hidden Gems of Plateau State",
    description: "Explore lesser-known attractions that make Jos special",
    date: "2024-03-08",
    duration: "38 mins",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&h=300&fit=crop",
    audioUrl: "#",
  },
  {
    id: 3,
    title: "The Business of Authentic Travel",
    description: "How to build a genuine tourism brand in competitive markets",
    date: "2024-03-01",
    duration: "52 mins",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&h=300&fit=crop",
    audioUrl: "#",
  },
];

export const blogPosts = [
  {
    id: 1,
    title: "10 Must-Try Dishes in Jos",
    excerpt: "Discover the authentic flavors that define Plateau cuisine",
    content: "Jos has a rich culinary heritage with unique dishes...",
    date: "2024-03-10",
    author: "Timothy Kunat",
    image: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=600&h=400&fit=crop",
    category: "Food",
  },
  {
    id: 2,
    title: "Traveling to Nigeria: A Beginner's Guide",
    excerpt: "Everything you need to know before visiting Nigeria",
    content: "Planning your first trip to Nigeria can be exciting...",
    date: "2024-03-05",
    author: "Timothy Kunat",
    image: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=600&h=400&fit=crop",
    category: "Travel Tips",
  },
  {
    id: 3,
    title: "The Art & Culture Scene in Jos",
    excerpt: "A deep dive into Jos's vibrant creative community",
    content: "Jos is home to some of Nigeria's most talented artists...",
    date: "2024-02-28",
    author: "Timothy Kunat",
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&h=400&fit=crop",
    category: "Culture",
  },
];

export const membershipPlans = [
  {
    id: 1,
    name: "Basic Explorer",
    price: 5000,
    period: "per month",
    description: "Start your discovery journey",
    features: [
      "Monthly newsletter with hidden gems",
      "10% discount on all tours",
      "Access to member-only blog posts",
      "Early access to new tours",
    ],
  },
  {
    id: 2,
    name: "Adventurer Pro",
    price: 12000,
    period: "per month",
    description: "Premium exploration experience",
    features: [
      "All Basic Explorer features",
      "Quarterly exclusive meetups",
      "20% discount on all tours",
      "Podcast listener community access",
      "Priority booking",
      "Personal travel consultation",
    ],
    popular: true,
  },
  {
    id: 3,
    name: "Elite Insider",
    price: 25000,
    period: "per month",
    description: "Complete access & experiences",
    features: [
      "All Adventurer Pro features",
      "Unlimited discount (40%) on tours",
      "Monthly private experiences",
      "VIP event invitations",
      "Direct access to Timothy",
      "Custom trip planning",
      "Exclusive merchandise",
    ],
  },
];
